version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  pre_build:
    
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'build'